services:

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: production
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test_tech_db


  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: production
      args:
        NEXT_PUBLIC_API_URL: /api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  app:
    driver: bridge
